import Config

# Configure your database
config :pidro_server, PidroServer.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "pidro_server_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pidro_server, PidroServerWeb.Endpoint,
  # Bind to all IPv4 interfaces so phones on the LAN can reach the API during
  # Expo device testing.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "pnGqjEwdCic/CHw5c4KllvXlUohV78Fxw7eymhSpAgelD/o9TB/fLUBYAzCKD1Nc",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pidro_server, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pidro_server, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :pidro_server, PidroServerWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/pidro_server_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :pidro_server, dev_routes: true

# Rate limits at 10x the production numbers so the frontend end-to-end harness
# can register several accounts from one address. Restated by hand because
# Config cannot read config.exs values; keep this table aligned with it.
#
#   policy                     production (config.exs)   dev (here)
#   login                      10 per 60_000 ms          100 per 60_000 ms
#   register                   10 per 600_000 ms         100 per 600_000 ms
#   password_reset             3 per 900_000 ms          30 per 900_000 ms
#   password_reset_identifier  3 per 3_600_000 ms        30 per 3_600_000 ms
#   password_reset_confirm     5 per 900_000 ms          50 per 900_000 ms
#   room_create                10 per 60_000 ms          100 per 60_000 ms
#   room_lookup                120 per 60_000 ms         1_200 per 60_000 ms
#   invite_mint                10 per 60_000 ms          100 per 60_000 ms
#   invite_preview             60 per 60_000 ms          600 per 60_000 ms
#   invite_redeem              10 per 60_000 ms          100 per 60_000 ms
#   guest_create               10 per 3_600_000 ms       100 per 3_600_000 ms
#   guest_create_daily         40 per 86_400_000 ms      400 per 86_400_000 ms
#   guest_create_install       3 per 3_600_000 ms        30 per 3_600_000 ms
#   room_join                  30 per 60_000 ms          300 per 60_000 ms
#   auth_upgrade               10 per 600_000 ms         100 per 600_000 ms
config :pidro_server, PidroServerWeb.Plugs.RateLimit,
  login: %{limit: 100, scale_ms: 60_000, key: :ip},
  register: %{limit: 100, scale_ms: 600_000, key: :ip},
  password_reset: %{limit: 30, scale_ms: 900_000, key: :ip},
  password_reset_identifier: %{limit: 30, scale_ms: 3_600_000, key: :identifier},
  password_reset_confirm: %{limit: 50, scale_ms: 900_000, key: :ip},
  room_create: %{limit: 100, scale_ms: 60_000, key: :user},
  room_lookup: %{limit: 1_200, scale_ms: 60_000, key: :ip},
  invite_mint: %{limit: 100, scale_ms: 60_000, key: :user},
  invite_preview: %{limit: 600, scale_ms: 60_000, key: :ip},
  invite_redeem: %{limit: 100, scale_ms: 60_000, key: :user},
  guest_create: %{limit: 100, scale_ms: 3_600_000, key: :ip},
  guest_create_daily: %{limit: 400, scale_ms: 86_400_000, key: :ip},
  guest_create_install: %{limit: 30, scale_ms: 3_600_000, key: :install_id},
  room_join: %{limit: 300, scale_ms: 60_000, key: :user},
  auth_upgrade: %{limit: 100, scale_ms: 600_000, key: :ip}

config :pidro_server, :password_reset,
  debug_tokens: true,
  reset_url_base: "http://localhost:5173"

# Invite links open the local landing page; INVITE_LINK_BASE_URL overrides.
config :pidro_server, PidroServer.Invites, link_base_url: "http://localhost:4000/j"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
