defmodule PidroServerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :pidro_server

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_pidro_server_key",
    signing_salt: "OHF91k4t",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # WebSocket for game channels
  socket "/socket", PidroServerWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :pidro_server,
    gzip: not code_reloading?,
    only: PidroServerWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :pidro_server
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # CORS configuration for mobile clients
  # Configure allowed origins in config/runtime.exs
  plug CORSPlug,
    origin: &PidroServerWeb.Endpoint.cors_origins/0,
    headers: ["Authorization", "Content-Type", "Accept"],
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

  plug PidroServerWeb.Router

  @doc """
  Returns the list of allowed CORS origins based on environment configuration.

  In development: allows all origins (*)
  In production: uses the CORS_ORIGINS environment variable (comma-separated list)
  """
  def cors_origins do
    case Application.get_env(:pidro_server, :cors_origins) do
      :all -> ["*"]
      origins when is_list(origins) -> origins
      _ -> ["*"]
    end
  end
end
